TRUNCATE TABLE Department;
INSERT INTO Department(NAME, ADDRESS, CODE, MEMBERS, ISRUNNING) VALUES ('研发', '1-1', '001', 5, 1);
INSERT INTO Department(NAME, ADDRESS, CODE, MEMBERS, ISRUNNING) VALUES ('销售', '1-2', '002', 15, 1);