-- DROP TABLE Department CASCADE CONSTRAINTS;

CREATE TABLE Department
(
    ID        NUMBER(15) GENERATED ALWAYS AS IDENTITY,
    NAME      VARCHAR2(100),
    ADDRESS   VARCHAR2(100),
    CODE      VARCHAR2(100),
    MEMBERS   NUMBER(15),
    ISRUNNING BOOLEAN
);
ALTER TABLE Department ADD CONSTRAINT PK_Department PRIMARY KEY (ID);